# Generated by Django 5.1 on 2024-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='attitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_teacher_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='conduct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='head_teacher_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
