# Generated by Django 5.1 on 2024-08-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
    ]
