# Generated by Django 5.1 on 2024-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studentprofile_attitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
